### ISSUE TITLE
Update static media assets to have a greater variety of shapes/sizes

### ISSUE THREAD

**Issue by ccasals** [phase2/outline#188]
Currently there are many P2 oriented stock images but they are all the same aspect ratio. This means that if you want a square or wide landscape image you need to upload new ones.

It would be great if there were a variety of image aspect ratios and the file names were clear on what that was (ie `square_400-400_headphones.jpg`)

**Comment by himerus** [comment]
Agreed we could use a larger variety (and usage) of images in our default components. 

This should include:
- ALL images are wrapped with a `<picture>` tag. This ensures consistency with either a simple image or a responsive one using `srcset`. 
- Samples of multiple responsive instances of images.
