### ISSUE TITLE
Links in card look like regular text

### ISSUE THREAD

**Issue by shaal** [phase2/outline#230]
Example:
https://outline.phase2tech.com/?path=/story/content-card--card-with-title-header

Hover above `Quis istum dolorem timet?`, and you'll noticed that it's a link but it looks like the rest of the text.

**Comment by himerus** [comment]
This should be easily resolved by wrapping the content with an `outline-styled-text` component, which will pass styles into the user generated content. We consider this to be like WYSIWYG content from the consumer. Who knows what they'll send us, so we cover all generic content styles with the mentioned component.
