### ISSUE TITLE
`<button>` should always have an explicit type (otherwise the default is `type="submit"`)

### ISSUE THREAD

**Issue by shaal** [phase2/outline#243]
TIL: https://twitter.com/BenLesh/status/1499767717703860232?s=20&t=z5tgbUQ0Dos7k0OEYJWgfw
![image](https://user-images.githubusercontent.com/22901/156814454-579dbf7c-027c-4933-a582-b3e39a4df9e5.png)

Unless a button is used to submit a form, we should always add `type="button"`

**Comment by himerus** [comment]
This should be easily resolved by wrapping the content with an `outline-styled-text` component, which will pass styles into the user generated content. We consider this to be like WYSIWYG content from the consumer. Who knows what they'll send us, so we cover all generic content styles with the mentioned component.

**Comment by himerus** [comment]
Held for additional work being done around the button presently.
