### ISSUE TITLE
[Feature]: Sunset Mobile Controller in Favor of Screensize Controller

### ISSUE THREAD

**Issue by mabry1985** [phase2/outline#331]
The Screensize handles a similar use case as the mobile controller, with more performant functionality,  and we should look at sunsetting it and replacing the existing implementations with the screensize controller.

**Comment by shaal** [comment]
Adding a link to ScreenSize Controller source code -https://github.com/phase2/outline/blob/next/src/components/controllers/screen-size-controller.ts
