### ISSUE TITLE
Accordion Component

### ISSUE THREAD

**Issue by himerus** [phase2/outline#37]
## Requirement
- Create an accordion component that is accessible called `outline-accordion`. 
- Accordion should have optional flag to have only one open, or many open. 

## Optional features
- I can set the header to use h1, h2, etc using the `outline-header` component
- I can set link to an accordion using an Anchor link
  - I can copy the link using the browser

### Example(s)
https://designsystem.digital.gov/components/accordion/
![Cursor_and_Accordion___U_S__Web_Design_System__USWDS_](https://user-images.githubusercontent.com/11083407/125134861-eb3c4080-e0bc-11eb-8478-e48a51c3050d.png)

### Accessibility Guidelines
[W3.org](https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html)
[A11y Style Guide](https://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-accordion)

**Comment by madhaze** [comment]
Do we need to have a way to select what heading level is used. 

Also check that we add keyboard functionally listed on https://www.w3.org/TR/wai-aria-practices-1.1/#accordion

**Comment by damontgomery** [comment]
Going to give this a shot.

**Comment by damontgomery** [comment]
Unassigned myself since @LeeMellon has #46 open.
