### ISSUE TITLE
Alert Component

### ISSUE THREAD

**Issue by LeeMellon** [phase2/outline#41]
## Requirements

Create an alert component that:

- Has large and small size options.
- Has an optional icon (can be hard coded for now until icon component is created/refined).
- Optional: Has basic style options like 'Warning", "Error" "Success" "Basic" (see below).

### Example 

- https://designsystem.digital.gov/components/alert/ 

![Alert___U_S__Web_Design_System__USWDS_](https://user-images.githubusercontent.com/11083407/125127028-d3f75600-e0b0-11eb-99f3-7fa4eda61fcb.png)

### Accessibility Guidelines
[W3.org](https://www.w3.org/TR/wai-aria-practices-1.1/examples/alert/alert.html)

**Comment by damontgomery** [comment]
Going to give this a shot.

**Comment by damontgomery** [comment]
Opened https://github.com/phase2/outline/pull/60.
