### ISSUE TITLE
Breadcrumb Component

### ISSUE THREAD

**Issue by LeeMellon** [phase2/outline#42]
## Requirements

Create a basic breadcrumb component that:

- Takes either a data array to render as links, or passes pre-rendered links into a slot.
- Conforms to accessibility guidelines.

### Example
https://designsystem.digital.gov/components/breadcrumb/
![Breadcrumb___U_S__Web_Design_System__USWDS_](https://user-images.githubusercontent.com/11083407/125129505-68af8300-e0b4-11eb-9a41-66223aabf1b0.png)

### Accessibility Guidelines 
[A11y Style Guide](https://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-breadcrumbs)
[W3.org](https://www.w3.org/TR/wai-aria-practices-1.1/examples/breadcrumb/index.html)

**Comment by sarahp** [comment]
Should we consider doing individual links instead of an array? The problem I'm having is drilling down into the `<ol>` to do the styling. I could use Tailwind classes if we're able to get that working in the main TS file. Thoughts?

**Comment by himerus** [comment]
We at least now have the slotted version, and should consider the data array option as an enhancement so we can do both.
