### ISSUE TITLE
Button Group

### ISSUE THREAD

**Issue by LeeMellon** [phase2/outline#44]
## Requirements

Create a basic button group component that:

- Takes pre-rendered instances of `outline-button` passed into a slot.
- Has basic 'Horizontal', 'Vertical' styling options.
- Meets accessibility standards.

### Example
https://designsystem.digital.gov/components/button-group/
![Button_group___U_S__Web_Design_System__USWDS_](https://user-images.githubusercontent.com/11083407/125132932-e88c1c00-e0b9-11eb-8e5d-229276f80cd9.png)

### Accessibility Guidelines
[a11y Style Guide](https://a11y-style-guide.com/style-guide/section-general.html#kssref-general-buttons) (also look at Tabs info?)
[Digital A11Y group role](https://www.digitala11y.com/group-role/)

### Notes/Questions
Not sure if we need to have some kind of state/change logic built into this component.
This should be actually simple to just pass in any number of buttons into a slot, and then based on a single property of horizontal/vertical alignment, you can swap CSS.

**Comment by himerus** [comment]
Discussed at Working Hours were a few things:

1.  Requirement / desire removed for JSON data to be accepted.
2. All items should just be `<outline-button>`'s passed into the default slot. 
3. Also [check out](https://github.com/phase2/outline/blob/next/src/components/base/outline-list/outline-list.ts) `outline-list` as an option to wrap the buttons and provide the functionality.
