### ISSUE TITLE
Modal Component

### ISSUE THREAD

**Issue by LeeMellon** [phase2/outline#45]
## Requirements

Create a basic modal component that:

- Can be closed via button or keyboard (esc key).
- Has small, medium, full screen sizes.
- At this stage passes all content into a slot.
- Meets accessibility standards.

### Examples
https://designsystem.digital.gov/components/modal/
![Modal___U_S__Web_Design_System__USWDS_](https://user-images.githubusercontent.com/11083407/125133930-6997e300-e0bb-11eb-93f4-f21f876f4777.png)

### Accessibility Guidelines
[W3.org](https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html)

**Comment by damontgomery** [comment]
This looks like it works pretty well. https://patternflyelements.org/components/modal/

**Comment by damontgomery** [comment]
#49 is ready for review.
