### ISSUE TITLE
Documentation: Using Outline in an existing application

### ISSUE THREAD

**Issue by scottalan** [phase2/outline#72]
## What files do you need to import into your application after you run a build of the Outline Design System?

1. **dist/outline.js**
2. **outline.theme.css**

_I'm not sure where the other **dist** files come into play but after including the aforementioned files in an existing application (React) I was able to successfully use the base Outline components in my React components_

**Comment by damontgomery** [comment]
Thanks for creating the issue!

Created #71 as an example with basic HTML. Does that seem like a decent starting point?

**Comment by scottalan** [comment]
Yep. This issue can be closed in favor of #71 . Thanks

**Comment by damontgomery** [comment]
#75 was opened since #71 was closed.
